version: '3.7'
services:
  backend:
    container_name: glt_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file: 
      - env_production.env
    ports:
      - '3001:3001'
  
  frontend:
    container_name: glt_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./frontend/src:/app/frontend/src
    stdin_open: true

  mongodb:
    container_name: glt_database
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    env_file: 
      - env_production.env
    volumes:
      - /data/db:/data/db
    ports:
      - '27017:27017'
