version: '3.7'

services:
  backend:
    container_name: ckd-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./backend/src:/app/backend/src
    env_file:
      - env_development.env

  frontend:
    container_name: ckd-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - '3001:3001'
    volumes:
      - ./frontend/src:/app/frontend/src
    stdin_open: true

  mongodb:
    container_name: ckd-database
    build:
      context: ./mongodb
    volumes:
      - /data/db:/data/db
    ports:
      - '27017:27017'
    env_file:
      - env_development.env
